#========== civcraft.net Server Listing Service (SLS) ==========#
use_server_listing_service: 'true'
#
server_address: "Your IP Here"
server_address_url: 'To A Website'
server_address_url_description: 'Description When Someone Hovers The Link'
#
server_name: 'Your Server Name'
server_name_url: 'To A Website'
server_name_url_description: 'Description When Someone Hovers The Link'
#
server_timezone: 'CST'
#
server_description: 'Anything you want!'
#
debug_heartbeat: 'false'
#=============== Database Configuration ===============#
mysql:
   hostname: localhost
   port: '3306'
   database: 'game'
   username: root
   password: 1234
   table_prefix: ''
   min_conns: '5'
   max_conns: '10'
   parts: '3'
#
global_database:
    database: 'global'
    hostname: localhost
    port: '3306'
    username: 'root'
    password: 1234
    min_conns: '5'
    max_conns: '10'
    parts: '3'
#
server_phase: 'TestServer'