#============> civcraft.net Server Listing Service (SLS) <============#
#True: on http://civilizationcraft.net/servers anyone can see your server
#False: Don't allow it to show on http://civilizationcraft.net/servers and
#you can use your own method to attract players.
use_server_listing_service: 'true'
#This is your server's IP. Players NEED this to connect.
server_address: "sls.example.com"
#What your server is called. (Clipped to 64 characters)
server_name: 'SLS Example Network'
#Your server's timezone. (Where it is hosted at) This can allow for players
#To decide to come here or choose a different one to fit their needs.
server_timezone: 'CST'
#A message to try and attract players. (Clipped to 128 characters)
server_description: 'Just another CivCraft server.'
#Prints a message to the console for every heartbeat packet sent to the server.
#This is useful for debugging.
debug_heartbeat: 'false'

#============> MySQL Database Configurlation <============#
# MySQL databases are used and required to have civcraft run.
#Change the username and password to fit what you called them!
mysql:
   hostname: localhost
   port: '3306'
   database: 'game'
   username: root
   password: 1234
   table_prefix: ''
   min_conns: '5'
   max_conns: '10'
   parts: '3'
#
global_database:
    database: 'global'
    hostname: localhost
    port: '3306'
    username: 'root'
    password: 1234
    min_conns: '5'
    max_conns: '10'
    parts: '3'

#This does nothing. Can be useful to track how many rounds/phases
#you reset of on your server!
server_phase: 'round1'
