name: CivCraft
main: com.civcraft.main.CivCraft
version: 1.2.0

commands:
    town:
        aliases: [t]
    plot:
        aliases: [p]
    resident:
        aliases: [res]
    dbg:
        aliases:
    accept:
        aliases: [yes]
    deny:
        aliases: [no]
    civ:
        aliases: [c]
    tc:
        aliases:
    cc:
        aliases:
    ac:
        aliases:
    gc:
        aliases:
    ad:
        aliases:
    build:
        aliases:
    market:
        aliases: [m]
    select:
        aliases:
    econ:
        aliases: [money]
    pay:
        aliases:
    here:
        aliases:
    camp:
        aliases:
    kill:
        aliases:
    sb:
        aliases:
